---
- name: "Converge"
  hosts: all
  become: true
  vars:
    - java_packages: [openjdk-8-jdk, openjdk-11-jdk]
    - java_home: /usr/lib/jvm/java-8-openjdk-amd64
  roles:
    - ansible-role-java
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false